Feat: 매거진 페이지 관리 : 삭제 기능
Kusitms-26th-Ohttention/pickRAP-FE pull request #38
Opened 2023-01-03 16:49 UTC by JJongsKim

## 📮 관련 이슈
- Resolved: #이슈번호

## ⛳️ 작업 내용

매거진 페이지 삭제 기능을 위한 작업을 했습니다.
- 매거진 다중 선택 UI 제작(이미 구현되어 있는 스크랩 다중 선택 참고)
- 다중 선택 시 Link 영향을 받지 않도록 조건문을 통해 관리
- 선택 버튼, 매거진 ids 배열을 recoil을 통해 관리 (선택을 취소할 시 ids 초기화, 선택했던 매거진 취소 시 ids에서 제외됨)

## 🌱 PR 포인트
- delete API를 사용한 작업은 현재 진행중입니다. 구현될 시 PR내용 수정하도록 하겠습니다!

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨부바람|

## 📎 레퍼런스

2023-01-08 15:29 UTC, elbica requested changes
최근에 일정이 있어서 리뷰가 늦었네요..😥
최대한 다 이해해보고 코멘트 남겼습니다~

확인해 보시고 제가 남긴 것들 한 번 고민해 보시면 좋겠습니다
고생 많으셨습니다😊

2023-01-08 15:29 UTC, elbica commented on src/components/magazine/MagazineList/TabMagazine.tsx
> +  const boolOption = option;
option, boolOption이란 변수가 네이밍만 봐서 어떤 일을 하는지 알기 어렵네요🥲
`multiSelect` 같은 네이밍이 어떨지 제안합니다~

2023-01-08 15:29 UTC, elbica commented on src/components/magazine/MagazineList/TabMagazine.tsx
> +  );
selector로 빼는 것도 좋아보여요
eslint 오류는 `[magazineItems, setMagazineItems]`로 디펜던시 넣으면 됩니다!

또한 `selectMagazineItems`는 인자로 들어온 id가 `magazineItems` 배열에 있으면 삭제하고, 반대로 없으면 추가하는 로직 같이 보이는데요

배열로 관리하는 것보다 `Set` 자료구조를 활용해 보시면 코드가 더 간단해질 것 같아요~

**예시 코드**
```tsx
// CategoryContentListMultiSelect.tsx
 const pickSet = useRef(new Set<number>());

pickSet.current.has(idx) ? pickSet.current.delete(idx) : pickSet.current.add(idx);

```

2023-01-08 15:29 UTC, elbica commented on src/components/magazine/MagazineList/TabMagazine.tsx
> +              )}
똑같은 `<Photo />` 컴포넌트가 반복되고 있네요!
```suggestion
            const Root = option ? <div /> : <Link href={`/magazine/${magazine.magazine_id}`} />;

          {cloneElement(Root, {
                  children: (
                    <Photo
                      blur={<PhotoSelect enabled={selectItem} />}
                      src={magazine.cover_url}
                      width={'196px'}
                      height={'255px'}
                      onClick={() => selectMagazineItems(magazine.magazine_id)}
                    />
                  ),
                })}
```
이런식으로도 해결 가능해 보입니다!

2023-01-08 15:29 UTC, elbica commented on src/containers/magazine/TabMagazineViewContainer.tsx
> +  const [option, isOption] = useRecoilState(deleteOption);
여기도 `option` 같은 추상적인 네이밍보다 모르는 사람이 읽기만 해도 어떤일을 하는지 알 수 있게 구체적으로 네이밍 하는 것이 좋아보입니다!

2023-01-08 15:29 UTC, elbica commented on src/containers/magazine/TabMagazineViewContainer.tsx
> +  }, [deleteState]);
`[deleteState, handleDeleteIds]`로 할 수 있을 것 같네요
eslint 오류 수정은 IDE 수준에서도 자동으로 고쳐주는 것으로 아는데 따로 eslint를 비활성시킨 이유가 있으실까요?

2023-01-08 15:29 UTC, elbica commented on src/infra/api/magazine.ts
> +    console.log('삭제확인용', `/magazine?ids=${ids}`);
디버깅용 콘솔로그는 지우는게 좋아보입니다!

2023-01-09 04:03 UTC, JJongsKim commented on src/containers/magazine/TabMagazineViewContainer.tsx
> +  }, [deleteState]);
deleteState 이외에 eslint 오류를 통해 추가해야 하는 디펜던시도 넣고, 
코드를 수정하다보니 마지막엔 API 무한요청으로 넘어가버려서 우선은 eslint 비활성 주석을 달아 놓았습니다!

2023-01-09 04:31 UTC, JJongsKim commented on src/components/magazine/MagazineList/TabMagazine.tsx
> +              )}
cloneElement 사용해서 저렇게 줄일 수 있는건 오늘 처음 알았네요!!
앞으로도 잘 참고할게요! 
map 안에서 돌아가고 있는 magazine_id 때문에, Root 선언이 안 될 것 같아서 일단 원래코드 사용하겠습니당!😭

2023-01-09 04:54 UTC, JJongsKim commented on src/components/magazine/MagazineList/TabMagazine.tsx
> +  );
Set을 활용하는 방법도 있었군요 !! 👀

2023-01-09 16:40 UTC, elbica reviewed
코멘트 남겼으니 한번 더 확인 부탁드립니다~😊

2023-01-09 16:40 UTC, elbica commented on src/components/magazine/MagazineList/TabMagazine.tsx
> +    [pickSet, setMagazineItems],
리액트의 ref는 변경이 일어나도 디펜던시 배열로 추적이 안돼서 리렌더링이 일어나지 않습니다
state와 다르게 mutable한 데이터이기 때문입니다

set이 바껴도 렌더링 결과엔 반영 안될 수 있다는 의미인데, ref 자체를 props로 전달하지 않는 한 디펜던시 배열에 넣는건 의미가 없습니다! 아실지도 모르겠지만 추후 다른 기능 개발 하실때 관련 문제 겪으실까봐 말씀드려요

여기선 recoil 상태와 동기화 시켜주기만 하니까 기능 동작엔 문제는 없어 보이네요

2023-01-09 16:40 UTC, elbica commented on src/containers/magazine/TabMagazineViewContainer.tsx
> +  deleteOption?: boolean;
props 구조분해할당을 보니 실제로 쓰이지 않는 옵션같은데 삭제하는게 좋아보여요
Option 이라는 네이밍도 사실 제가 보기엔 유의미한 정보를 전달해 주지 않는 추상적인 네이밍 같아 보이긴 합니다

props 네이밍 하실때 일반적인 인터페이스는 유지해야 하지만 (value, onClick) 추상적인 단어(manager, process, xxxoption..)는 지양하는게 좋을 것 같아요!

2023-01-09 16:40 UTC, elbica commented on src/containers/magazine/TabMagazineViewContainer.tsx
> +  }, [deleteState]);
지금 api 무한요청은 해결된 상태인데 eslint 비활성 주석은 예상치 못한 동작 방지를 위해서라도 없애는게 좋을 듯 합니다
혹시 아직도 무한요청이 발생하나요...?

2023-01-09 16:40 UTC, elbica commented on src/components/magazine/MagazineList/TabMagazine.tsx
> +  const [, setMagazineItems] = useRecoilState(magazineIdsArray);
state 부분을 사용하고 있지 않으니useSetRecoilState를 쓰는게 좋겠네요!

2023-01-09 16:43 UTC, elbica approved these changes

2023-01-10 00:24 UTC, JJongsKim commented on src/containers/magazine/TabMagazineViewContainer.tsx
> +  deleteOption?: boolean;
아 어떻게 네이밍 할 때 효과적일지 관련해서도 공부를 좀 해야겠네요!
넵 반영해서 수정하겠습니당!

2023-01-10 02:30 UTC, JJongsKim commented on src/containers/magazine/TabMagazineViewContainer.tsx
> +  }, [deleteState]);
제가 boolean state를 하나 놓치고 있었던 게 있어서 무한요청이 발생했었습니다!
해당 사항은 수정하였고, 디펜던시들도 추가하여 ESLint 오류없도록 만들어 다시 푸시했습니당😁

2023-01-10 03:08 UTC, merged